// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for ListNotesParamsSort.
const (
	ListNotesParamsSortCreatedAt      ListNotesParamsSort = "createdAt"
	ListNotesParamsSortId             ListNotesParamsSort = "id"
	ListNotesParamsSortMinusCreatedAt ListNotesParamsSort = "-createdAt"
	ListNotesParamsSortMinusId        ListNotesParamsSort = "-id"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewNote defines model for NewNote.
type NewNote struct {
	Content string `json:"content"`
}

// Note defines model for Note.
type Note struct {
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
	WordCount int       `json:"wordCount"`
}

// NoteList defines model for NoteList.
type NoteList struct {
	Data []Note `json:"data"`

	// HasMore Whether more results exist after this page
	HasMore bool `json:"hasMore"`

	// Limit Maximum results per page
	Limit int `json:"limit"`

	// NextCursor Opaque cursor to pass as 'after' for the next page (present only when hasMore is true)
	NextCursor *string `json:"nextCursor,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// After Opaque cursor returned by a previous page (pass the nextCursor value)
	After *string `form:"after,omitempty" json:"after,omitempty"`

	// Limit Maximum number of results per page (default 20, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Sort Sort order for results. Prefix with - for descending.
	// Default: id (ascending by ID).
	Sort *ListNotesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListNotesParamsSort defines parameters for ListNotes.
type ListNotesParamsSort string

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody = NewNote

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = NewNote
